### ISSUE TITLE
Xray texturepack not being blocked in modded server

### ISSUE THREAD

**Issue by ianespana** [Yeregorix/Mirage#47]
Hey, so, I've had some issues with cheaters as of late, and they appear to be using this texture pack to get xray capabilities: https://www.curseforge.com/minecraft/texture-packs/xray-ultimate-1-11-compatible

I have installed it myself and indeed the ores still show up, regardless of what modifier I use (Well, except hidden, but that's not useful for me). I am utilizing version 1.3.17 with SpongeForge 7.3.0. Config is included below

![image](https://user-images.githubusercontent.com/3208876/100117465-6e649b00-2e3a-11eb-9dfb-c026ffcd1f38.png)

[Link to configuration](https://pastebin.com/M7JWxwSp)

**Comment by ianespana** [comment]
On second thought, it looks like it is working, however blocks exposed to air are visible regardless of distance to the player. Maybe there'd be a way to fix that by making a check around the player to see if ores are within a certain radius?

**Comment by Yeregorix** [comment]
Hi, you're correct, blocks exposed to air are visible because they need to be so that legit players can see them. There is a way to hide these ores outside a specific radius, this is called dynamism and it is already enabled in your config. Currently, the radius is set to 6 chunks (6×16=96 blocks) in your last modifier.
There are two solutions to your problem:
1: Decrease the radius. However the smaller is the radius, the more legit players may be affected.
2: Change your last modifier type from `obvious` to `random` and add `minecraft:stone` in the blocks list. This will generate thousands fake ores that will hide the few real ones.

**Comment by ianespana** [comment]
Ah. I like the way you think. Drown them in a sea of ores. Thanks!
