### ISSUE TITLE
Improving the setCenter method

### ISSUE THREAD

**Issue by Gershon123** [Yeregorix/Mirage#49]
The setCenter method seems to be called on the player movement & player rotation packets. Is it possible to put it into an async scheduler?
![image](https://user-images.githubusercontent.com/78274963/106365174-6b35d180-62f9-11eb-87d1-c873a89020ee.png)

**Comment by Yeregorix** [comment]
This method interacts with objects that are modified synchronously, mostly NetworkBlockContainer and PlayerChunkMapEntry. While I guess it's not impossible to make dynamism async, it's quite difficult to make it correctly and would need many synchronization points. I'm not sure it would improves performance significantly, plus I expect some issues to appear because of block changes being handled concurrently. 

I definitely not have the time to explore this possibility for Mirage on Sponge API 7, I might think about it when rewriting the plugin for API 8.
